# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
  
  # Zipping up
    - run: |
        sudo apt-get install zip
        zip -qq -r $(basename $GITHUB_REPOSITORY)-$GITHUB_RUN_ID.zip *
        
    - uses: chrislennon/action-aws-cli@v1.1
      # All commands after this point have access to the AWS CLI     
    - run: aws s3 cp *.zip s3://sandbox-demo-artifact-repository/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - run: |
        aws ec2 run-instances \
        --region us-east-2 \
        --image-id ami-0c57643465a38057b \
        --instance-type t2.medium \
        --subnet-id subnet-e289d998 \
        --security-group-ids sg-0253fcb17f2622914 \
        --associate-public-ip-address \
        --key-name wmg-sandbox-2020-10-12 \
        --user-data file://deploy_scripts/deploy.sh \
        --iam-instance-profile Name=Allow-S3-Artifact-Repository \
        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=FrontEnd},{Key=Artifact,Value=s3://sandbox-demo-artifact-repository/$(basename $GITHUB_REPOSITORY)-$GITHUB_RUN_ID.zip}]"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
